# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-02 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatwhat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='eatwhat.Category'),
        ),
    ]
