# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatwhat', '0002_auto_20180602_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eatwhat.Category'),
        ),
    ]
