# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatwhat', '0003_auto_20180602_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='school',
        ),
        migrations.AddField(
            model_name='food',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eatwhat.School'),
            preserve_default=False,
        ),
    ]
