# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-02 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eatwhat', '0005_auto_20180603_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eatwhat.School'),
        ),
    ]
